name: quality_system
description: Quality System Application For TIE India
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  # api_request
  http: ^0.13.5
  equatable: ^2.0.5
  easy_debounce: ^2.0.2+1

  # fonts
  google_fonts: ^3.0.1

  # loading
  flutter_spinkit: ^5.1.0

  # formatting
  font_awesome_flutter: ^10.3.0
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  from_css_color: ^2.0.0
  timeago: ^3.3.0
  page_transition: ^2.0.9
  show_more_text_popup: ^0.3.0

  json_path: ^0.4.2

  # redirect
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/login_images/
    - images/variant_images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
